name: flutter_application_api_bloc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  animated_splash_screen: ^1.3.0

  # Firebase stable versions compatible with Kotlin 1.9
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^19.5.0

  shared_preferences: ^2.5.3
  flutter_localization: ^0.3.3
  intl: ^0.19.0
  uuid: ^4.5.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  workmanager: ^0.7.0
  get_it: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pictures/
    - assets/icons/
    - assets/sounds/
  fonts:
    - family: Lexend_Deca
      fonts:
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend_Deca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
